services:
  request-bin:
    image: ghcr.io/kingsukhoi/request-bin:latest
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_URL: postgres://postgres:yourpassword@postgres:5432/request_bin?sslmode=disable
      GIN_MODE: release
      CUSTOM_ROUTES: "/test-wtf"
    depends_on:
      - postgres
    networks:
      - postgres-network

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"

    environment:
      POSTGRES_MULTIPLE_DATABASES: request_bin,wtf_inator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/multiple_pg_db.sh:/docker-entrypoint-initdb.d/multiple_pg_db.sh
    networks:
      - postgres-network

  # Jaeger services
  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector HTTP
      - "14250:14250"  # Jaeger collector gRPC
      - "4318:4318"    # OTLP HTTP receiver
      - "4317:4317"    # OTLP gRPC receiver
      - "6831:6831/udp"  # Jaeger agent UDP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - postgres-network

volumes:
  postgres_data:
  valkey_data:

networks:
  postgres-network:
    driver: bridge
