### Health check request bin
GET localhost:8081/healthz

### Health check request bin
GET localhost:8081/

### try proxy
POST http://localhost:1323/test-wtf?id=hi
Content-Type: application/json

{
  "farsos": "be testing"
}

### try response code
POST http://localhost:1323/respCode/500?test=query
Content-Type: application/json

{
  "farsos": "be testing"
}

### Health check through proxy
GET http://localhost:1323/healthz
Content-Type: application/json


