// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Request struct {
	ID          uuid.UUID          `json:"id"`
	Method      string             `json:"method"`
	Content     []byte             `json:"content"`
	SourceIp    string             `json:"sourceIp"`
	Timestamp   pgtype.Timestamptz `json:"timestamp"`
	RequestPath string             `json:"requestPath"`
}

type RequestHeader struct {
	RequestID uuid.UUID   `json:"requestId"`
	Name      string      `json:"name"`
	Value     pgtype.Text `json:"value"`
}

type RequestQueryParameter struct {
	RequestID uuid.UUID   `json:"requestId"`
	Name      string      `json:"name"`
	Value     pgtype.Text `json:"value"`
}

type Response struct {
	Requestid       uuid.UUID          `json:"requestid"`
	ResponseContent []byte             `json:"responseContent"`
	ResponseCode    int32              `json:"responseCode"`
	Timestamp       pgtype.Timestamptz `json:"timestamp"`
}

type ResponseHeader struct {
	Requestid uuid.UUID   `json:"requestid"`
	Name      string      `json:"name"`
	Value     pgtype.Text `json:"value"`
}
